'use client';
import { report } from './report-data';

const pct=(n:number)=>`${(n/35*100).toFixed(1).replace('.',',')}%`;
function Donut({kind}:{kind:'areas'|'industries'}){const data=report[kind];let cursor=0;const stops=data.map(d=>{const start=cursor;cursor+=d[1]/35*360;return `${d[2]} ${start}deg ${cursor}deg`}).join(',');return <div className="donut" style={{background:`conic-gradient(${stops})`}} role="img" aria-label={`Distribución de 35 ofertas por ${kind==='areas'?'área':'industria'}`}><div><strong>35</strong><span>ofertas</span></div></div>}
function Chart({kind}:{kind:'areas'|'industries'}){return <div className="chart"><Donut kind={kind}/><div className="legend">{report[kind].map(([label,n,color])=><div className="legendRow" key={label}><i style={{background:color}}/><span>{label}</span><b>{n} <small>{pct(n)}</small></b></div>)}</div></div>}
const Head=({number,title,children}:{number:string;title:string;children?:React.ReactNode})=><div className="sectionHead"><div><div className="kicker">{number}</div><h2>{title}</h2></div>{children&&<div className="sectionCopy">{children}</div>}</div>;

export default function Home(){return <>
 <header className="top"><a href="#inicio" className="brand">✳ <span>UTN.BA</span></a><nav aria-label="Navegación principal"><a href="#contexto">Contexto</a><a href="#resultados">Resultados</a><a href="#diagnostico">Diagnóstico</a><a href="#recomendaciones">Recomendaciones</a></nav><a className="download" href="/Informe-Ejecutivo-Pasantias-UTNBA.pdf" download>Descargar informe</a></header>
 <main>
  <section id="inicio" className="hero reportPage"><div className="eyebrow">Informe ejecutivo · Primera gestión</div><h1>Gestión del Módulo<br/>de Pasantías</h1><p className="lead">Primer mes de actividad del módulo de pasantías en el portal Talentia UTN.BA.</p><div className="heroMeta"><span><b>Período</b>{report.period}</span><span><b>Institución</b>Facultad Regional Buenos Aires</span></div><div className="scroll">Desplazá para recorrer el informe ↓</div></section>
  <section className="intro reportPage"><Head number="01 · Resumen" title="Una primera lectura del desempeño"><p>Este informe visualiza y analiza el primer mes de gestión del módulo de pasantías en UTN.BA.</p></Head><div className="statement"><b>Mensaje central</b><p>La adopción tecnológica inicial muestra un alto interés estudiantil. El crecimiento y la activación de convenios dependen principalmente de la gestión interna de las personas responsables de Extensión y de Ingenierías, más allá de las capacidades del software provisto.</p></div></section>
  <section id="contexto" className="light reportPage"><Head number="02 · Contexto Operativo y Gestión" title="Un primer mes para medir, ordenar y proyectar"><p><b>Período evaluado.</b> Primer mes de operación del Módulo de Pasantías, del 13 de julio al 13 de agosto, en el portal Talentia UTN.BA.</p></Head><div className="editorialGrid"><article><span>Objetivo estratégico</span><p>{report.objective}</p></article><article><span>Alcance institucional</span><p>{report.institution}. La gestión abarca carreras de grado de la Secretaría de Ingeniería y tecnicaturas y carreras de grado de Extensión Universitaria.</p></article></div></section>
  <section className="dark reportPage"><Head number="03 · Contexto del Mercado y Marco Legal" title="Una modalidad con escala y reglas definidas"><p>El mercado de pasantías conecta la demanda empresarial de talento joven con la búsqueda estudiantil de experiencia profesional relevante.</p></Head><div className="marketGrid">{report.market.map(m=><article key={m.label}><strong>{m.value}</strong><span>{m.label}</span>{m.note&&<small>{m.note}</small>}</article>)}</div><p className="sourceNote">Las cifras de 6,9 millones, 2% y 126.000 son estimaciones de mercado consignadas por el documento fuente. El dato de 6,26 millones se atribuye al SIPA.</p></section>
  <section className="light reportPage"><Head number="04 · Marco regulatorio" title="Ley Nacional de Pasantías N.º 26.427"><p>La normativa estructura el modelo de gestión y delimita destinatarios, carga horaria, asignación estímulo y gastos administrativos.</p></Head><div className="legalGrid"><article><b>Población objetivo</b><p>Estudiantes regulares de tecnicaturas, terciarios y carreras universitarias que cumplan los requisitos de su plan de estudios.</p></article><article><b>Asignación estímulo</b><p>Suma no remunerativa proporcional a la carga horaria, con un máximo de 20 horas semanales. Se toma como base el convenio colectivo aplicable o, en su ausencia, el SMVM.</p></article><article><b>Gastos administrativos</b><p>La institución educativa puede percibir hasta un 5% del valor de la asignación estímulo en concepto de gastos administrativos.</p></article></div></section>
  <section id="resultados" className="light reportPage"><Head number="05 · Métricas del Primer Mes y Datos Duros de Gestión" title="Actividad e interés estudiantil"><p>El portal reunió 506 postulaciones en 35 ofertas impulsadas por 20 empresas: un promedio de 14,5 postulaciones por búsqueda.</p></Head><div className="metrics">{report.metrics.map(m=><article key={m.label}><strong>{m.value}</strong><span>{m.label}</span></article>)}</div><div className="callout"><span>1</span><div><b>Pasantía activa en curso</b><p>Jerónimo Becker · Furlong Incoming S.A. · del 06/04/2026 al 06/10/2026.</p></div></div><p className="companyExamples"><b>Empresas participantes.</b> La actividad incluye firmas de tecnología, manufactura, retail y logística, entre ellas Toyota, Renault, IBM, Lenovo, Biogénesis Bagó y Furlong Incoming.</p></section>
  <section className="dark reportPage"><Head number="06 · Desglose de la demanda" title="La tecnología concentra la mayor parte de las búsquedas"><p>Sistemas, desarrollo y software explican el 42,9% de las ofertas. La demanda también alcanza ingeniería, marketing, finanzas, ventas, administración, logística y producto.</p></Head><Chart kind="areas"/></section>
  <section className="light reportPage"><Head number="07 · Ofertas por industria" title="Una demanda distribuida entre tecnología e industria"><p>Tecnología representa 14 de las 35 ofertas, seguida por registros sin especificar y manufactura.</p></Head><Chart kind="industries"/><p className="note">Nota metodológica: el PDF fuente consigna Retail como 4 (8,6%), una combinación internamente inconsistente. Para preservar el total de 35 y el porcentaje publicado, esta reconstrucción utiliza 3 ofertas.</p></section>
  <section className="academic reportPage"><Head number="08 · Oferta Académica y Rubros de Inserción Profesional" title="Nueve ingenierías sostienen una base amplia de perfiles"><p>Secretaría de Ingeniería · 9 carreras de grado.</p></Head><div className="degreeGrid">{report.engineering.map(([name,detail])=><article key={name}><b>{name}</b><span>{detail}</span></article>)}</div></section>
  <section className="light reportPage"><Head number="08 · Oferta Académica y Rubros de Inserción Profesional" title="Extensión amplía el alcance a tecnología, gestión y ambiente"><p>Secretaría de Extensión Universitaria · 16 trayectos de tecnicatura, grado y posgrado informados por el documento.</p></Head><div className="extensionGrid">{report.extension.map(g=><article key={g.group}><h3>{g.group}</h3><ul>{g.items.map(i=><li key={i}>{i}</li>)}</ul></article>)}</div></section>
  <section id="diagnostico" className="diagnosis reportPage"><Head number="09 · Diagnóstico Actual: El Potencial Oculto y la Autonomía de Gestión de UTN BA" title="El potencial está en activar la cartera existente"/><div className="bigStats"><article><strong>771</strong><span>organizaciones registradas</span></article><article><strong>38</strong><span>con convenio firmado en plataforma</span></article><article><strong>104</strong><span>convenios marco informados en la cartera institucional</span></article></div><div className="twoCol"><p><b>Brecha de digitalización.</b> La incorporación de las empresas restantes no depende de una limitación de Talentia: requiere digitalizar convenios físicos bajo gestión administrativa de la Universidad.</p><p><b>Oportunidad inmediata.</b> El Word estima que podrían sumarse unas 70 empresas y señala un universo superior a 700 cuentas sin convenio vigente como canal propio de expansión.</p></div></section>
  <section className="light reportPage"><Head number="10 · Empresas con Convenio Firmado en Plataforma" title="38 organizaciones ya tienen el marco habilitado"><p>La nómina corresponde exclusivamente a empresas con convenio firmado y usuario activo dentro de la plataforma.</p></Head><div className="companyGrid">{report.companies.map(c=><span key={c}>{c}</span>)}</div></section>
  <section className="forecast reportPage"><Head number="11 · Pronóstico y Proyecciones" title="La escalabilidad depende de la agilidad interna"><p>La activación de la cartera no requiere desarrollos externos: depende de procesar los convenios en papel hacia el entorno digital.</p></Head><div className="forecastBody"><article><b>Escalabilidad independiente</b><p>La tecnología ya está disponible e implementada. El crecimiento puede acelerarse mediante la organización administrativa y la activación total de los convenios marco firmados.</p></article><article><b>Optimización y mejora de ingresos</b><p>La base de pasantes históricos y la posibilidad de evaluar esquemas de recupero administrativo —dentro del tope legal del 5%— abren una oportunidad para incrementar recursos y hacer más eficientes los procesos.</p></article></div></section>
  <section id="recomendaciones" className="recommend reportPage"><Head number="12 · Recomendaciones" title="Un marco común, con gestión operativa autónoma"/><div className="recommendGrid"><article><b>01</b><h3>Convenio Marco Unificado</h3><p>Mantener un único paraguas legal para Ingenierías y Extensión transmite solidez institucional y permite descubrir perfiles de diferentes disciplinas.</p></article><article><b>02</b><h3>Independencia y separación operativa</h3><p>Gestionar acuerdos individuales en módulos separados permite que cada área administre estudiantes con autonomía, normas y ritmos propios.</p></article><article><b>03</b><h3>Digitalización de convenios</h3><p>Evaluar el traspaso progresivo de los 104 convenios institucionales al entorno digital, de acuerdo con las capacidades administrativas.</p></article></div></section>
  <section className="recommend reportPage"><Head number="12 · Recomendaciones" title="Activar empresas y ampliar oportunidades"><p>El universo de más de 770 organizaciones permite construir una estrategia de continuidad desde la propia Facultad.</p></Head><div className="recommendGrid"><article><b>04</b><h3>Acercamiento comercial</h3><p>Comunicar a las empresas con convenio vigente y cargado que ya tienen la oportunidad habilitada para contratar pasantes mediante el portal.</p></article><article><b>05</b><h3>Nuevas carreras</h3><p>La demanda en sistemas, marketing, finanzas, ventas y administración amplía oportunidades para carreras y tecnicaturas de Extensión.</p></article><article><b>06</b><h3>Continuidad de gestión</h3><p>Capitalizar el potencial mediante activación sostenida, responsabilidades claras y seguimiento de convenios y acuerdos individuales.</p></article></div></section>
  <footer><div className="brand">✳ <span>UTN.BA</span></div><p>Gestión del Módulo de Pasantías · Talentia</p><p>{report.period}</p></footer>
 </main></>}
