'use client';
import { report } from './report-data';

const pct=(n:number)=>`${(n/35*100).toFixed(1).replace('.',',')}%`;
function Donut({kind}:{kind:'areas'|'industries'}){const data=report[kind];let cursor=0;const stops=data.map(d=>{const start=cursor;cursor+=d[1]/35*360;return `${d[2]} ${start}deg ${cursor}deg`}).join(',');return <div className="donut" style={{background:`conic-gradient(${stops})`}} role="img" aria-label={`Distribución de 35 ofertas por ${kind==='areas'?'área':'industria'}`}><div><strong>35</strong><span>ofertas</span></div></div>}
function Chart({kind}:{kind:'areas'|'industries'}){return <div className="chart"><Donut kind={kind}/><div className="legend">{report[kind].map(([label,n,color])=><div className="legendRow" key={label}><i style={{background:color}}/><span>{label}</span><b>{n} <small>{pct(n)}</small></b></div>)}</div></div>}
const Head=({number,title,children}:{number:string;title:string;children?:React.ReactNode})=><div className="sectionHead"><div><div className="kicker">{number}</div><h2>{title}</h2></div>{children&&<div className="sectionCopy">{children}</div>}</div>;

export default function Home(){return <>
 <header className="top"><a href="#inicio" className="brand">✳ <span>UTN.BA</span></a><nav aria-label="Navegación principal"><a href="#contexto">Contexto</a><a href="#resultados">Resultados</a><a href="#analisis">Análisis</a><a href="#recomendaciones">Recomendaciones</a></nav><a className="download" href="/Informe-Ejecutivo-Pasantias-UTNBA.pdf" download>Descargar informe</a></header>
 <main>
  <section id="inicio" className="hero reportPage"><div className="eyebrow">Informe ejecutivo · Primera gestión</div><h1>Gestión del Módulo<br/>de Pasantías</h1><p className="lead">Primer mes de actividad del módulo de pasantías en el portal Talentia UTN.BA.</p><div className="heroMeta"><span><b>Período</b>{report.period}</span><span><b>Institución</b>Facultad Regional Buenos Aires</span></div><div className="scroll">Desplazá para recorrer el informe ↓</div></section>
  <section className="intro reportPage"><Head number="01 · Resumen" title="Una primera lectura del desempeño"><p>Analizar el primer mes de gestión permite dimensionar la adopción del módulo, reconocer la respuesta estudiantil y establecer prioridades para la siguiente etapa.</p></Head><div className="statement"><b>Mensaje central</b><p>Se observa una adopción tecnológica inicial acompañada por un alto interés estudiantil. Para transformar esa tracción en mayor cantidad de oportunidades, resulta prioritario fortalecer la gestión interna, coordinar a las áreas de Extensión e Ingenierías y acelerar la activación administrativa de los convenios.</p></div></section>
  <section id="contexto" className="light reportPage"><Head number="02 · Contexto Operativo y Gestión" title="Un primer mes para medir, ordenar y proyectar"><p><b>Período evaluado.</b> Primer mes de operación del Módulo de Pasantías, del 13 de julio al 13 de agosto, en el portal Talentia UTN.BA. Se propone establecer una línea de base para evaluar evolución, capacidad operativa y nivel de adopción.</p></Head><div className="editorialGrid"><article><span>Objetivo estratégico</span><p>{report.objective}</p></article><article><span>Alcance institucional</span><p>{report.institution}. Integrar las carreras de grado de la Secretaría de Ingeniería con las tecnicaturas y carreras de Extensión Universitaria permite ampliar la diversidad de perfiles disponibles y responder a una demanda laboral transversal.</p></article></div></section>
  <section className="dark reportPage"><Head number="03 · Contexto del Mercado y Marco Legal" title="Una modalidad con escala y reglas definidas"><p>El mercado de pasantías articula la necesidad empresarial de incorporar talento joven con la búsqueda estudiantil de experiencia profesional relevante. Su escala potencial justifica consolidar una capacidad institucional específica para gestionar vínculos, oportunidades y acuerdos.</p></Head><div className="marketGrid">{report.market.map(m=><article key={m.label}><strong>{m.value}</strong><span>{m.label}</span>{m.note&&<small>{m.note}</small>}</article>)}</div><p className="sourceNote">Como referencia de escala, se estima que las pasantías representan alrededor del 2% de las relaciones laborales, equivalente a unas 126.000 experiencias activas. A abril de 2025, el empleo asalariado privado registrado alcanza 6,26 millones de personas.</p></section>
  <section className="light reportPage"><Head number="04 · Marco regulatorio" title="Ley Nacional de Pasantías N.º 26.427"><p>La normativa estructura el modelo de gestión y delimita destinatarios, carga horaria, asignación estímulo y gastos administrativos.</p></Head><div className="legalGrid"><article><b>Población objetivo</b><p>Estudiantes regulares de tecnicaturas, terciarios y carreras universitarias que cumplan los requisitos de su plan de estudios.</p></article><article><b>Asignación estímulo</b><p>Suma no remunerativa proporcional a la carga horaria, con un máximo de 20 horas semanales. Se toma como base el convenio colectivo aplicable o, en su ausencia, el SMVM.</p></article><article><b>Gastos administrativos</b><p>La institución educativa puede percibir hasta un 5% del valor de la asignación estímulo en concepto de gastos administrativos.</p></article></div></section>
  <section id="resultados" className="light reportPage"><Head number="05 · Métricas del Primer Mes y Datos Duros de Gestión" title="Actividad e interés estudiantil"><p>El portal reunió 506 postulaciones en 35 ofertas impulsadas por 20 empresas: un promedio de 14,5 postulaciones por búsqueda.</p></Head><div className="metrics">{report.metrics.map(m=><article key={m.label}><strong>{m.value}</strong><span>{m.label}</span></article>)}</div><div className="callout"><span>1</span><div><b>Pasantía activa en curso</b><p>Jerónimo Becker · Furlong Incoming S.A. · del 06/04/2026 al 06/10/2026.</p></div></div><p className="companyExamples"><b>Empresas participantes.</b> La actividad incluye firmas de tecnología, manufactura, retail y logística, entre ellas Toyota, Renault, IBM, Lenovo, Biogénesis Bagó y Furlong Incoming.</p></section>
  <section className="dark reportPage"><Head number="06 · Desglose de la demanda" title="La tecnología concentra la mayor parte de las búsquedas"><p>Sistemas, desarrollo y software explican el 42,9% de las ofertas. La demanda también alcanza ingeniería, marketing, finanzas, ventas, administración, logística y producto.</p></Head><Chart kind="areas"/></section>
  <section className="light reportPage"><Head number="07 · Ofertas por industria" title="Una demanda distribuida entre tecnología e industria"><p>Tecnología representa 14 de las 35 ofertas, seguida por manufactura y por búsquedas que aún no cuentan con una clasificación sectorial específica. Se identifica una base diversificada, con participación adicional de retail y energía.</p></Head><Chart kind="industries"/><p className="note">Profundizar la normalización de categorías permitirá mejorar la lectura sectorial, comparar períodos y orientar acciones de vinculación con mayor precisión.</p></section>
  <section className="academic reportPage"><Head number="08 · Oferta Académica y Rubros de Inserción Profesional" title="Nueve ingenierías sostienen una base amplia de perfiles"><p>Secretaría de Ingeniería · 9 carreras de grado.</p></Head><div className="degreeGrid">{report.engineering.map(([name,detail])=><article key={name}><b>{name}</b><span>{detail}</span></article>)}</div></section>
  <section className="light reportPage"><Head number="08 · Oferta Académica y Rubros de Inserción Profesional" title="Extensión amplía el alcance a tecnología, gestión y ambiente"><p>Secretaría de Extensión Universitaria · 16 trayectos de tecnicatura, grado y posgrado. Incorporar esta diversidad académica permite responder a búsquedas que exceden las ingenierías tradicionales y ampliar la propuesta de valor institucional frente a las empresas.</p></Head><div className="extensionGrid">{report.extension.map(g=><article key={g.group}><h3>{g.group}</h3><ul>{g.items.map(i=><li key={i}>{i}</li>)}</ul></article>)}</div></section>
  <section id="analisis" className="diagnosis reportPage"><Head number="09 · Análisis Actual: El Potencial Oculto y la Autonomía de Gestión de UTN BA" title="El potencial está en activar la cartera existente"/><div className="bigStats"><article><strong>771</strong><span>organizaciones registradas</span></article><article><strong>38</strong><span>con convenio firmado en plataforma</span></article><article><strong>104</strong><span>convenios marco en la cartera institucional</span></article></div><div className="twoCol"><p><b>Brecha de digitalización.</b> Se identifica una diferencia significativa entre la cartera institucional y las empresas que ya operan digitalmente. Reducir esa brecha requiere ordenar, actualizar y digitalizar convenios bajo una gestión administrativa coordinada.</p><p><b>Oportunidad inmediata.</b> Se estima un potencial de incorporación cercano a 70 empresas mediante la activación de convenios existentes. A su vez, más de 700 organizaciones registradas sin convenio vigente conforman un canal propio para desarrollar nuevas relaciones institucionales.</p></div></section>
  <section className="light reportPage"><Head number="10 · Empresas con Convenio Firmado en Plataforma" title="38 organizaciones ya tienen el marco habilitado"><p>La nómina corresponde exclusivamente a empresas con convenio firmado y usuario activo dentro de la plataforma.</p></Head><div className="companyGrid">{report.companies.map(c=><span key={c}>{c}</span>)}</div></section>
  <section className="forecast reportPage"><Head number="11 · Pronóstico y Proyecciones" title="La escalabilidad depende de la agilidad interna"><p>Para ampliar la cartera activa no se requieren desarrollos tecnológicos adicionales. Se necesita convertir la disponibilidad técnica existente en una capacidad operativa sostenida, con responsables, prioridades y tiempos de gestión definidos.</p></Head><div className="forecastBody"><article><b>Escalabilidad independiente</b><p>Acelerar la digitalización y activación de convenios permite crecer con autonomía, reducir tiempos administrativos y ampliar el volumen de oportunidades sin depender de nuevas implementaciones externas.</p></article><article><b>Optimización y mejora de ingresos</b><p>Evaluar esquemas de recupero administrativo dentro del tope legal del 5% permite fortalecer la sostenibilidad del servicio. Para avanzar, resulta necesario definir criterios institucionales, trazabilidad operativa y mecanismos transparentes de administración.</p></article></div></section>
  <section id="recomendaciones" className="recommend reportPage"><Head number="12 · Recomendaciones" title="Un marco común, con gestión operativa autónoma"/><div className="recommendGrid"><article><b>01</b><h3>Convenio Marco Unificado</h3><p>Mantener un único paraguas legal para Ingenierías y Extensión transmite solidez institucional y permite descubrir perfiles de diferentes disciplinas.</p></article><article><b>02</b><h3>Independencia y separación operativa</h3><p>Gestionar acuerdos individuales en módulos separados permite que cada área administre estudiantes con autonomía, normas y ritmos propios.</p></article><article><b>03</b><h3>Digitalización de convenios</h3><p>Evaluar el traspaso progresivo de los 104 convenios institucionales al entorno digital, de acuerdo con las capacidades administrativas.</p></article></div></section>
  <section className="recommend reportPage"><Head number="12 · Recomendaciones" title="Activar empresas y ampliar oportunidades"><p>El universo de más de 770 organizaciones permite construir una estrategia de continuidad liderada por la Facultad, combinando activación administrativa, acompañamiento institucional y ampliación de perfiles.</p></Head><div className="recommendGrid"><article><b>04</b><h3>Acompañamiento institucional</h3><p>Diseñar una comunicación segmentada para informar a las empresas con convenio vigente que ya pueden publicar búsquedas y contratar pasantes. Acompañar la activación con orientación operativa y seguimiento.</p></article><article><b>05</b><h3>Nuevas carreras</h3><p>Extender la participación a carreras y tecnicaturas vinculadas con sistemas, marketing, finanzas, ventas y administración, alineando la oferta académica con la demanda observada.</p></article><article><b>06</b><h3>Continuidad de gestión</h3><p>Establecer responsables, metas de activación e indicadores periódicos para sostener el crecimiento, monitorear convenios y evaluar resultados por área académica.</p></article></div></section>
  <footer><div className="brand">✳ <span>UTN.BA</span></div><p>Gestión del Módulo de Pasantías · Talentia</p><p>{report.period}</p></footer>
 </main></>}
